[2023-06-22T11:41:25.892+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.orders manual__2023-06-22T11:36:16.320737+00:00 [queued]>
[2023-06-22T11:41:25.900+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.orders manual__2023-06-22T11:36:16.320737+00:00 [queued]>
[2023-06-22T11:41:25.901+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-22T11:41:25.932+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_task.source.development.sales_stage.orders> on 2023-06-22 11:36:16.320737+00:00
[2023-06-22T11:41:25.936+0000] {standard_task_runner.py:57} INFO - Started process 81208 to run task
[2023-06-22T11:41:25.940+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt', 'dbt_task.source.development.sales_stage.orders', 'manual__2023-06-22T11:36:16.320737+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpvw7wpbeu']
[2023-06-22T11:41:25.941+0000] {standard_task_runner.py:85} INFO - Job 216: Subtask dbt_task.source.development.sales_stage.orders
[2023-06-22T11:41:26.001+0000] {task_command.py:410} INFO - Running <TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.orders manual__2023-06-22T11:36:16.320737+00:00 [running]> on host ubuntu.thbnzb0d3dmuziyfg2t53bofqb.tx.internal.cloudapp.net
[2023-06-22T11:41:26.284+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt' AIRFLOW_CTX_TASK_ID='dbt_task.source.development.sales_stage.orders' AIRFLOW_CTX_EXECUTION_DATE='2023-06-22T11:36:16.320737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-22T11:36:16.320737+00:00'
[2023-06-22T11:41:26.286+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-22T11:41:26.286+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "cd /home/satyam/airflow/dags/dbt/ && dbt run --models bronze_orders --vars 'run_date: 2023-06-22T00:00:00+00:00'"]
[2023-06-22T11:41:26.294+0000] {subprocess.py:86} INFO - Output:
[2023-06-22T11:41:28.809+0000] {subprocess.py:93} INFO - [0m11:41:28  Running with dbt=1.5.1
[2023-06-22T11:41:29.200+0000] {subprocess.py:93} INFO - [0m11:41:29  Unable to do partial parsing because config vars, config profile, or config target have changed
[2023-06-22T11:41:30.423+0000] {subprocess.py:93} INFO - [0m11:41:30  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-22T11:41:30.423+0000] {subprocess.py:93} INFO - There are 3 unused configuration paths:
[2023-06-22T11:41:30.423+0000] {subprocess.py:93} INFO - - models.development.bronze
[2023-06-22T11:41:30.423+0000] {subprocess.py:93} INFO - - models.development.staging
[2023-06-22T11:41:30.423+0000] {subprocess.py:93} INFO - - models.development.intermediate
[2023-06-22T11:41:30.441+0000] {subprocess.py:93} INFO - [0m11:41:30  Found 7 models, 0 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 4 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-22T11:41:30.443+0000] {subprocess.py:93} INFO - [0m11:41:30
[2023-06-22T11:41:32.338+0000] {subprocess.py:93} INFO - [0m11:41:32  Concurrency: 1 threads (target='dev')
[2023-06-22T11:41:32.339+0000] {subprocess.py:93} INFO - [0m11:41:32
[2023-06-22T11:41:32.344+0000] {subprocess.py:93} INFO - [0m11:41:32  1 of 1 START sql incremental model final_sales.bronze_orders ................... [RUN]
[2023-06-22T11:41:32.964+0000] {subprocess.py:93} INFO - [0m11:41:32  1 of 1 ERROR creating sql incremental model final_sales.bronze_orders .......... [[31mERROR[0m in 0.62s]
[2023-06-22T11:41:32.968+0000] {subprocess.py:93} INFO - [0m11:41:32
[2023-06-22T11:41:32.969+0000] {subprocess.py:93} INFO - [0m11:41:32  Finished running 1 incremental model in 0 hours 0 minutes and 2.52 seconds (2.52s).
[2023-06-22T11:41:32.981+0000] {subprocess.py:93} INFO - [0m11:41:32
[2023-06-22T11:41:32.982+0000] {subprocess.py:93} INFO - [0m11:41:32  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-22T11:41:32.983+0000] {subprocess.py:93} INFO - [0m11:41:32
[2023-06-22T11:41:32.983+0000] {subprocess.py:93} INFO - [0m11:41:32  [33mDatabase Error in model bronze_orders (models/sales/bronze/bronze_orders.sql)[0m
[2023-06-22T11:41:32.984+0000] {subprocess.py:93} INFO - [0m11:41:32    001003 (42000): SQL compilation error:
[2023-06-22T11:41:32.984+0000] {subprocess.py:93} INFO - [0m11:41:32    syntax error line 7 at position 16 unexpected '00'.
[2023-06-22T11:41:32.985+0000] {subprocess.py:93} INFO - [0m11:41:32    syntax error line 7 at position 28 unexpected '00'.
[2023-06-22T11:41:32.985+0000] {subprocess.py:93} INFO - [0m11:41:32    compiled Code at target/run/development/models/sales/bronze/bronze_orders.sql
[2023-06-22T11:41:32.986+0000] {subprocess.py:93} INFO - [0m11:41:32
[2023-06-22T11:41:32.986+0000] {subprocess.py:93} INFO - [0m11:41:32  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-06-22T11:41:34.487+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-22T11:41:34.496+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-22T11:41:34.499+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=airflow_dbt, task_id=dbt_task.source.development.sales_stage.orders, execution_date=20230622T113616, start_date=20230622T114125, end_date=20230622T114134
[2023-06-22T11:41:34.523+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 216 for task dbt_task.source.development.sales_stage.orders (Bash command failed. The command returned a non-zero exit code 1.; 81208)
[2023-06-22T11:41:34.572+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-22T11:41:34.725+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
